version: '3.7'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/node/app/
    container_name: fetch
    command: npm run start
    ports:
      - '8080:80'
